# Generated by Django 3.2.4 on 2021-06-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210623_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Краткое название')),
                ('content', models.TextField(verbose_name='Сама новость')),
                ('source', models.FloatField(default=0, verbose_name='Источник новости')),
                ('contacts', models.TextField(verbose_name='Связаться с автором новости')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_time_stamp_path, verbose_name='Изображение к новости')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводит в списке?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опублекована')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор новости')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subrubric', verbose_name='Рубрика новостей')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости астрономии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=main.utilities.get_time_stamp_path, verbose_name='Изображение')),
                ('astrImg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.astrofiles', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
