# Generated by Django 3.2.4 on 2021-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_addimages_astrofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrofiles',
            name='source',
            field=models.CharField(max_length=40, verbose_name='Источник новости'),
        ),
    ]
