# Generated by Django 3.2.4 on 2021-06-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_astrofiles_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addimages',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='astrofiles',
            name='contacts',
            field=models.CharField(max_length=40, verbose_name='Связаться с автором новости'),
        ),
    ]
