# Generated by Django 3.2.4 on 2021-06-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210623_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddImages',
            new_name='AdditionalImage',
        ),
        migrations.RenameModel(
            old_name='AstroFiles',
            new_name='Bb',
        ),
        migrations.RenameField(
            model_name='additionalimage',
            old_name='astrImg',
            new_name='bb',
        ),
    ]
