# Generated by Django 3.2.4 on 2021-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210623_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Краткое название'),
        ),
    ]
